### ISSUE TITLE
Oversampling of a polynomial bug

### ISSUE THREAD

**Issue by Vadimuh** [Simsso/Online-Tools#14] opened 2020-02-29 07:17 UTC
If one inputs the following points:
```
0 0
1 0
2 0
3 1
4 4
5 10
6 20
7 35
8 56
```

The equation the tool generates is an 8th degree polynomial, whereas this actually should be a 3rd degree polynomial (The exact polynomial is "n choose 3").
Granted, the polynomial the tool generates has very small coefficients for powers 4, ..., 8
Which leads me to believe that this is as a result of natural error in floating point representation of numbers.

I'm thinking there's probably two ways to handle these cases. One is to have your matrix operations utilize rationals (as in, full precision, store numerator and denominator) instead of floating point values. The other would be to have the output ignore terms in the polynomial which have very small coefficients (perhaps configurable by the user too).

**Comment by Simsso** [comment] 2020-03-01 17:37
Thanks for reporting the problem. I am able to reproduce it (see screenshot).

The two solutions you offer both seem reasonable. The latter is more of a "fix", however, much easier to implement. I'll see what I can do and keep this issue updated.

![image](https://user-images.githubusercontent.com/6556307/75630511-ad3b2c80-5beb-11ea-9c8f-615eebc7b0c9.png)
_Screenshot of the polynomial with very small coefficients._

**Comment by Simsso** [comment] 2020-04-05 21:29
Fixed in https://github.com/Simsso/Online-Tools/commit/778b1cc1e3a05a5e52aa6ba488b84cb45fe6d164. I went with the simple option, because the other one would simply be too much workload given my priorities right now.

For the provided example, the equation is now nice and short:  
![image](https://user-images.githubusercontent.com/6556307/78510409-2e5e8400-7795-11ea-913f-cfccf91d51d7.png)
_Screenshot of the polynomial with very small coefficients (updated)._

**Closed as completed** 2020-04-07 21:33 UTC
Labels: enhancement, bug
